included:
  - Weave

excluded:
  - vendor
  - Resources

disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - nesting

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional
  - unused_import

identifier_name:
  min_length:
    warning: 1
  excluded:
    - id
    - i
    - x
    - y
    - s
    - c
    - pr

large_tuple:
  warning: 3
